### ISSUE TITLE
Logger throws errors unless the plugin folder is named "massacre"

### ISSUE THREAD

**Issue by ElSaico** [CMDR-WDX/EDMC-Massacres#13]
o7, CMDR!

While setting up my dev environment in order to make a plugin, I saw yours throwing several errors at the console - all of them similar to this:

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\__init__.py", line 440, in format
    return self._format(record)
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\__init__.py", line 436, in _format
    return self._fmt % values
KeyError: 'osthreadid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\handlers.py", line 196, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\__init__.py", line 650, in formatMessage
    return self._style.format(record)
  File "C:\Users\bm229\.pyenv\pyenv-win\versions\3.10.4\lib\logging\__init__.py", line 442, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'osthreadid'
Call stack:
  File "C:\Users\bm229\Projects\EDMarketConnector\EDMarketConnector.py", line 2024, in <module>
    app = AppWindow(root)
  File "C:\Users\bm229\Projects\EDMarketConnector\EDMarketConnector.py", line 518, in __init__
    appitem = plugin.get_app(frame)
  File "C:\Users\bm229\Projects\EDMarketConnector\plug.py", line 84, in get_app
    appitem = plugin_app(parent)
  File "C:\Users\bm229\AppData\Local\EDMarketConnector\plugins\EDMC-Massacres-2.0.2\load.py", line 19, in plugin_app
    ui.set_frame(parent)
  File "C:\Users\bm229\AppData\Local\EDMarketConnector\plugins\EDMC-Massacres-2.0.2\massacre\ui.py", line 251, in set_frame
    self.update_ui()
  File "C:\Users\bm229\AppData\Local\EDMarketConnector\plugins\EDMC-Massacres-2.0.2\massacre\ui.py", line 283, in update_ui
    logger.info("UI Update done")
Message: 'UI Update done'
Arguments: ()
```

Searching around led me to EDCD/EDMarketConnector#1357, which explains that the logger name must feature the name of the plugin's root folder - something the developer documentation makes clearer now:

```py
plugin_name = os.path.basename(os.path.dirname(__file__))

# A Logger is used per 'found' plugin to make it easy to include the plugin's
# folder name in the logging output format.
# NB: plugin_name here *must* be the plugin's folder name as per the preceding
#     code, else the logger won't be properly set up.
logger = logging.getLogger(f'{appname}.{plugin_name}')
```

**Comment by CMDR-WDX** [comment]
Thank you for your very detailed Issue. 

I have made some changes ( see #14 ) to define the plugin name dynamically.

I renamed the directory locally and it no longer resulted in an Error.
Could you please check out on https://github.com/CMDR-WDX/EDMC-Massacres/tree/ed80a6aea721f1667dcc360c1c72f2c7d1d4b030 and see if the issue has been resolved for you?

**Comment by ElSaico** [comment]
> Thank you for your very detailed Issue.
> 
> I have made some changes ( see #14 ) to define the plugin name dynamically.
> 
> I renamed the directory locally and it no longer resulted in an Error. Could you please check out on https://github.com/CMDR-WDX/EDMC-Massacres/tree/ed80a6aea721f1667dcc360c1c72f2c7d1d4b030 and see if the issue has been resolved for you?

Finally got around to check 😅 but yes, that fixes it.
