### ISSUE TITLE
Sum/Wing Sum Total Miscounting

### ISSUE THREAD

**Issue by YoteZip** [CMDR-WDX/EDMC-Massacres#15]
Hello, the sum total of mission rewards and the sum total of wing rewards appear to be wrong, and I think I see the bug.

For context, here is a current mission setup I have:
![image](https://user-images.githubusercontent.com/118632916/208497331-ae8b8438-9740-419a-bccf-095ecee54ce8.png)

and a readout from another tool that shows all the data correctly ([EDCarnage](https://github.com/mmomtchev/edcarnage)):
![image](https://user-images.githubusercontent.com/118632916/208497482-1cd8d5b0-aee5-42c7-b696-155064889591.png)

Notably, all the data within each faction's row is accurate, but the totaling at the end is off massively (it displays 1176.9 instead of 549.5, which is the number the second tool calculates and the number that can also be reached by manually totaling all the rows).

I think the problem is here: https://github.com/CMDR-WDX/EDMC-Massacres/blob/master/massacre/ui.py#L38-L48
![image](https://user-images.githubusercontent.com/118632916/208498933-83644b56-a620-4ca2-abe5-ef06a774d401.png)

Where line 38 pulls the existing reward count from the faction, line 41 then adds another mission's reward to it, then line 48 adds that number to the sum. When it loops back to line 38 again, it starts with the faction's reward count from previous iterations and adds that to the sum again along with the current iteration's mission, instead of starting at e.g. 0

In practice I think this would result in e.g. for the top faction on the second screenshot:
1. sum += 30.145m
2. sum += 30.145m + 21.550m
3. sum += 30.145m + 21.550m + 21.571m
4. sum += 30.145m + 21.550m + 21.571m + 15.947m
5. sum += 30.145m + 21.550m + 21.571m + 15.947m + 41.112m

I wasn't sure how to start debugging EDMC outputs by myself to confirm this is what's happening, and depending on the order that EDMC iterates through the missions you can get different answers, but this is what I suspect is going on. Either way, there is a problem with the totals, and if this isn't the problem then something else is causing it.

**Comment by CMDR-WDX** [comment]
Hey @YoteZip 

Thank you for this very detailed Issue.
Your assessment was correct. I think I have fixed the bug with the changes made in https://github.com/CMDR-WDX/EDMC-Massacres/commit/62dce98a407dc28e59d06aa0e0f559de9e71ddc2. 

I do not have a massacre stack currently set up, so I would kindly ask you to try and replace the following version of [ui.py](https://github.com/CMDR-WDX/EDMC-Massacres/blob/62dce98a407dc28e59d06aa0e0f559de9e71ddc2/massacre/ui.py), ([raw version](https://raw.githubusercontent.com/CMDR-WDX/EDMC-Massacres/62dce98a407dc28e59d06aa0e0f559de9e71ddc2/massacre/ui.py)) with the one on your EDMC-Massacres Plugin.
The file in question can be found under `%localappdata%\EDMarketConnector\plugins\EDMC-Massacres\massacre\ui.py` 

In this file I have also added a Log entry to print the `massacre_state` provided to the `MassacreMissionData` class.
So if there are still issues, I would kindly ask you to set your EDMC's Logging Level to debug. 

This can be done under `File > Settings > Configuration Tab` At the Bottom there is a Log Level. Set that to "Debug".
The next time the UI is updated with a new massacre state, the data provided to that class will be printed to the most recent log file in `%TEMP%\EDMarketConnector` In that file you can Ctrl+F for "MASSACRE_MISSION_DATA_INPUT" and copy the line below here.

**Comment by YoteZip** [comment]
Hello, it just reports "Missing Active Mission Data" and crashes with a JSON serialization error. I'm not sure if the code will work after this is resolved, but in case you're still having problems, I've been using a temporary fix with the following, which seems to work:
![image](https://user-images.githubusercontent.com/118632916/208710154-d2a098c7-0956-4008-9dba-338f73da180b.png)


But I don't know much about the codebase so idk if this is potentially causing issues elsewhere.

The crash log is below:
```log
-12-20 15:51:22.502 UTC - WARNING - 1812164:139995188680512:1812164 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.mission_repository.MissionRepository.notify_about_active_mission_uuids:81: Mission UUIDs were passed even though the State is already initialized
2022-12-20 15:51:22.503 UTC - INFO - 1812164:139995188680512:1812164 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.massacre_mission_state.__handle_new_missions_state:92: Received a new Missions State with 18 Missions.
2022-12-20 15:51:22.503 UTC - INFO - 1812164:139995188680512:1812164 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.massacre_mission_state.__handle_new_missions_state:97: 18 of found Missions are Massacre Missions
2022-12-20 15:51:22.503 UTC - DEBUG - 1812164:139995188680512:1812164 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.ui.MassacreMissionData.__init__:22: MassacreMissionData input below: MASSACRE_MISSION_DATA_INPUT
2022-12-20 15:51:22.503 UTC - ERROR - 1812164:139995188680512:1812164 plug.notify_journal_entry:315: Plugin "EDMC-Massacres-15-sumwing-sum-total-miscounting" failed
Traceback (most recent call last):
  File "/mnt/Games/Local/Elite Dangerous/EDMarketConnector/plug.py", line 312, in notify_journal_entry
    newerror = journal_entry(cmdr, is_beta, system, station, dict(entry), dict(state))
  File "/home/user/.local/share/EDMarketConnector/plugins/EDMC-Massacres-15-sumwing-sum-total-miscounting/load.py", line 54, in journal_entry
    set_active_uuids(list(active_mission_uuids), cmdr)
  File "/home/user/.local/share/EDMarketConnector/plugins/EDMC-Massacres-15-sumwing-sum-total-miscounting/massacre/mission_repository.py", line 136, in set_active_uuids
    mission_repository.notify_about_active_mission_uuids(_active_uuids, cmdr)
  File "/home/user/.local/share/EDMarketConnector/plugins/EDMC-Massacres-15-sumwing-sum-total-miscounting/massacre/mission_repository.py", line 97, in notify_about_active_mission_uuids
    listener(self._active_missions)
  File "/home/user/.local/share/EDMarketConnector/plugins/EDMC-Massacres-15-sumwing-sum-total-miscounting/massacre/massacre_mission_state.py", line 107, in __handle_new_missions_state
    listener(_massacre_mission_store)
  File "/home/user/.local/share/EDMarketConnector/plugins/EDMC-Massacres-15-sumwing-sum-total-miscounting/massacre/ui.py", line 349, in handle_new_massacre_mission_state
    data_view = MassacreMissionData(data)
  File "/home/user/.local/share/EDMarketConnector/plugins/EDMC-Massacres-15-sumwing-sum-total-miscounting/massacre/ui.py", line 23, in __init__
    logger.debug(json.dumps(massacre_state))
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MassacreMission is not JSON serializable
```

**Comment by CMDR-WDX** [comment]
Oh I see. Give me 10 mins :)

**Comment by CMDR-WDX** [comment]
@YoteZip 
I have updated ui.py and massacre_mission_state.py

You can find the new version here:
https://raw.githubusercontent.com/CMDR-WDX/EDMC-Massacres/15-sumwing-sum-total-miscounting/massacre/ui.py
https://raw.githubusercontent.com/CMDR-WDX/EDMC-Massacres/15-sumwing-sum-total-miscounting/massacre/massacre_mission_state.py

**Comment by YoteZip** [comment]
Hello, I now get this output:
![image](https://user-images.githubusercontent.com/118632916/208716892-7d9b930e-8e85-43be-a8ca-d8300611774c.png)

Here is a detailed mission summary if it helps:
![image](https://user-images.githubusercontent.com/118632916/208717022-8739f548-4206-4a66-88a7-76d5485d5270.png)

Here is the log:
```
2022-12-20 16:31:23.459 UTC - WARNING - 1857999:140080373479232:1857999 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.mission_repository.MissionRepository.notify_about_active_mission_uuids:81: Mission UUIDs were passed even though the State is already initialized
2022-12-20 16:31:23.460 UTC - INFO - 1857999:140080373479232:1857999 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.massacre_mission_state.__handle_new_missions_state:105: Received a new Missions State with 18 Missions.
2022-12-20 16:31:23.460 UTC - INFO - 1857999:140080373479232:1857999 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.massacre_mission_state.__handle_new_missions_state:110: 18 of found Missions are Massacre Missions
2022-12-20 16:31:23.460 UTC - DEBUG - 1857999:140080373479232:1857999 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.ui.MassacreMissionData.__init__:22: MassacreMissionData input below: MASSACRE_MISSION_DATA_INPUT
2022-12-20 16:31:23.460 UTC - DEBUG - 1857999:140080373479232:1857999 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.ui.MassacreMissionData.__init__:28: {"906554952": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906554952, "target_faction": "LP 932-12 Society", "count": 25, "reward": 30914056, "target_system": "LP 932-12", "source_faction": "Bureau of Gliese 868 Law Party", "is_wing": false}, "906554964": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906554964, "target_faction": "LP 932-12 Society", "count": 72, "reward": 34840688, "target_system": "LP 932-12", "source_faction": "LFT 1 Confederacy", "is_wing": true}, "906555406": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906555406, "target_faction": "LP 932-12 Society", "count": 25, "reward": 30448206, "target_system": "LP 932-12", "source_faction": "Bureau of Gliese 868 Law Party", "is_wing": false}, "906555408": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906555408, "target_faction": "LP 932-12 Society", "count": 15, "reward": 20474866, "target_system": "LP 932-12", "source_faction": "Gliese 868 Services", "is_wing": false}, "906555419": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906555419, "target_faction": "LP 932-12 Society", "count": 20, "reward": 21504502, "target_system": "LP 932-12", "source_faction": "Gliese 868 Industries", "is_wing": false}, "906574288": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906574288, "target_faction": "LP 932-12 Society", "count": 30, "reward": 41355460, "target_system": "LP 932-12", "source_faction": "Gliese 868 Services", "is_wing": false}, "906578912": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906578912, "target_faction": "LP 932-12 Society", "count": 30, "reward": 41473348, "target_system": "LP 932-12", "source_faction": "Union of Gliese 868 Green Party", "is_wing": false}, "906578923": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906578923, "target_faction": "LP 932-12 Society", "count": 30, "reward": 40553888, "target_system": "LP 932-12", "source_faction": "Izumo Heavy Industries Ltd", "is_wing": false}, "906578929": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906578929, "target_faction": "LP 932-12 Society", "count": 25, "reward": 30270418, "target_system": "LP 932-12", "source_faction": "Union of Gliese 868 Green Party", "is_wing": false}, "906579154": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906579154, "target_faction": "LP 932-12 Society", "count": 15, "reward": 20410032, "target_system": "LP 932-12", "source_faction": "Izumo Heavy Industries Ltd", "is_wing": false}, "906579167": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906579167, "target_faction": "LP 932-12 Society", "count": 17, "reward": 15775837, "target_system": "LP 932-12", "source_faction": "Gliese 868 Services", "is_wing": false}, "906579901": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906579901, "target_faction": "LP 932-12 Society", "count": 25, "reward": 30730732, "target_system": "LP 932-12", "source_faction": "Bureau of Gliese 868 Law Party", "is_wing": false}, "906579909": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906579909, "target_faction": "LP 932-12 Society", "count": 30, "reward": 41228524, "target_system": "LP 932-12", "source_faction": "Union of Gliese 868 Green Party", "is_wing": false}, "906579918": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906579918, "target_faction": "LP 932-12 Society", "count": 25, "reward": 30504268, "target_system": "LP 932-12", "source_faction": "Gliese 868 Services", "is_wing": false}, "906580160": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906580160, "target_faction": "LP 932-12 Society", "count": 25, "reward": 30829526, "target_system": "LP 932-12", "source_faction": "Gliese 868 Services", "is_wing": false}, "906580203": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906580203, "target_faction": "LP 932-12 Society", "count": 63, "reward": 30450910, "target_system": "LP 932-12", "source_faction": "Izumo Heavy Industries Ltd", "is_wing": true}, "906581378": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906581378, "target_faction": "LP 932-12 Society", "count": 42, "reward": 20284144, "target_system": "LP 932-12", "source_faction": "LFT 1 Confederacy", "is_wing": true}, "906581385": {"target_type": "$MissionUtil_FactionTag_Pirate;", "mission_id": 906581385, "target_faction": "LP 932-12 Society", "count": 64, "reward": 30765050, "target_system": "LP 932-12", "source_faction": "Gliese 868 Industries", "is_wing": true}}
2022-12-20 16:31:23.460 UTC - INFO - 1857999:140080373479232:1857999 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.ui.UI.update_ui:322: Updating UI...
2022-12-20 16:31:23.463 UTC - INFO - 1857999:140080373479232:1857999 <plugins>.EDMC-Massacres-15-sumwing-sum-total-miscounting.massacre.ui.UI.update_ui:339: UI Update done
```

And here's the JSON it dumped:
```json
{
    "906554952": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906554952,
        "target_faction": "LP 932-12 Society",
        "count": 25,
        "reward": 30914056,
        "target_system": "LP 932-12",
        "source_faction": "Bureau of Gliese 868 Law Party",
        "is_wing": false
    },
    "906554964": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906554964,
        "target_faction": "LP 932-12 Society",
        "count": 72,
        "reward": 34840688,
        "target_system": "LP 932-12",
        "source_faction": "LFT 1 Confederacy",
        "is_wing": true
    },
    "906555406": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906555406,
        "target_faction": "LP 932-12 Society",
        "count": 25,
        "reward": 30448206,
        "target_system": "LP 932-12",
        "source_faction": "Bureau of Gliese 868 Law Party",
        "is_wing": false
    },
    "906555408": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906555408,
        "target_faction": "LP 932-12 Society",
        "count": 15,
        "reward": 20474866,
        "target_system": "LP 932-12",
        "source_faction": "Gliese 868 Services",
        "is_wing": false
    },
    "906555419": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906555419,
        "target_faction": "LP 932-12 Society",
        "count": 20,
        "reward": 21504502,
        "target_system": "LP 932-12",
        "source_faction": "Gliese 868 Industries",
        "is_wing": false
    },
    "906574288": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906574288,
        "target_faction": "LP 932-12 Society",
        "count": 30,
        "reward": 41355460,
        "target_system": "LP 932-12",
        "source_faction": "Gliese 868 Services",
        "is_wing": false
    },
    "906578912": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906578912,
        "target_faction": "LP 932-12 Society",
        "count": 30,
        "reward": 41473348,
        "target_system": "LP 932-12",
        "source_faction": "Union of Gliese 868 Green Party",
        "is_wing": false
    },
    "906578923": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906578923,
        "target_faction": "LP 932-12 Society",
        "count": 30,
        "reward": 40553888,
        "target_system": "LP 932-12",
        "source_faction": "Izumo Heavy Industries Ltd",
        "is_wing": false
    },
    "906578929": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906578929,
        "target_faction": "LP 932-12 Society",
        "count": 25,
        "reward": 30270418,
        "target_system": "LP 932-12",
        "source_faction": "Union of Gliese 868 Green Party",
        "is_wing": false
    },
    "906579154": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906579154,
        "target_faction": "LP 932-12 Society",
        "count": 15,
        "reward": 20410032,
        "target_system": "LP 932-12",
        "source_faction": "Izumo Heavy Industries Ltd",
        "is_wing": false
    },
    "906579167": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906579167,
        "target_faction": "LP 932-12 Society",
        "count": 17,
        "reward": 15775837,
        "target_system": "LP 932-12",
        "source_faction": "Gliese 868 Services",
        "is_wing": false
    },
    "906579901": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906579901,
        "target_faction": "LP 932-12 Society",
        "count": 25,
        "reward": 30730732,
        "target_system": "LP 932-12",
        "source_faction": "Bureau of Gliese 868 Law Party",
        "is_wing": false
    },
    "906579909": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906579909,
        "target_faction": "LP 932-12 Society",
        "count": 30,
        "reward": 41228524,
        "target_system": "LP 932-12",
        "source_faction": "Union of Gliese 868 Green Party",
        "is_wing": false
    },
    "906579918": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906579918,
        "target_faction": "LP 932-12 Society",
        "count": 25,
        "reward": 30504268,
        "target_system": "LP 932-12",
        "source_faction": "Gliese 868 Services",
        "is_wing": false
    },
    "906580160": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906580160,
        "target_faction": "LP 932-12 Society",
        "count": 25,
        "reward": 30829526,
        "target_system": "LP 932-12",
        "source_faction": "Gliese 868 Services",
        "is_wing": false
    },
    "906580203": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906580203,
        "target_faction": "LP 932-12 Society",
        "count": 63,
        "reward": 30450910,
        "target_system": "LP 932-12",
        "source_faction": "Izumo Heavy Industries Ltd",
        "is_wing": true
    },
    "906581378": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906581378,
        "target_faction": "LP 932-12 Society",
        "count": 42,
        "reward": 20284144,
        "target_system": "LP 932-12",
        "source_faction": "LFT 1 Confederacy",
        "is_wing": true
    },
    "906581385": {
        "target_type": "$MissionUtil_FactionTag_Pirate;",
        "mission_id": 906581385,
        "target_faction": "LP 932-12 Society",
        "count": 64,
        "reward": 30765050,
        "target_system": "LP 932-12",
        "source_faction": "Gliese 868 Industries",
        "is_wing": true
    }
}
```

**Comment by CMDR-WDX** [comment]
Thank you. I will take a closer look into this

**Comment by CMDR-WDX** [comment]
Okay. I got it fixed :) 
I had moved the sum aggregation, but forgot to remove the old assignment. oh well :D 

I have bundled up the version below. If it gives the correct result for you, I would merge the changes and set up a new version.
[EDMC-Massacres-v2.0.3-pre1.zip](https://github.com/CMDR-WDX/EDMC-Massacres/files/10270942/EDMC-Massacres-v2.0.3-pre1.zip)

**Comment by YoteZip** [comment]
Looks correct to me:
![image](https://user-images.githubusercontent.com/118632916/208734337-20cb2a7b-c5cb-4031-af13-c007ef64f624.png)

and a read out from EDCarnage:
![image](https://user-images.githubusercontent.com/118632916/208734392-262169e4-1cfc-4fb2-ab81-1b0154c544e2.png)
